name: Docker Build and Push to ACR

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_REGISTRY_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.ACR_REGISTRY_URL }}/rizzerve:latest
          ${{ secrets.ACR_REGISTRY_URL }}/rizzerve:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.ACR_REGISTRY_URL }}/rizzerve:buildcache
        cache-to: type=registry,ref=${{ secrets.ACR_REGISTRY_URL }}/rizzerve:buildcache,mode=max
