name: Trigger auto deployment for rizzerve-deploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/rizzerve-deploy-AutoDeployTrigger-e7c173aa-cdc5-45b9-ae55-f6de86bfbe30.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RIZZERVEDEPLOY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RIZZERVEDEPLOY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RIZZERVEDEPLOY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: rizzerve.azurecr.io
          registryUsername: ${{ secrets.RIZZERVEDEPLOY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RIZZERVEDEPLOY_REGISTRY_PASSWORD }}
          containerAppName: rizzerve-deploy
          resourceGroup: rizzerve
          imageToBuild: rizzerve.azurecr.io/rizzerve-deploy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


